/**
 * @fileoverview gRPC-Web generated client stub for org.example.ProyectoGrpc.grpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: usuario.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.org = {};
proto.org.example = {};
proto.org.example.ProyectoGrpc = {};
proto.org.example.ProyectoGrpc.grpc = require('./usuario_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.Usuario,
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 */
const methodDescriptor_UsuarioService_AltaUsuario = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/AltaUsuario',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.Usuario,
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.Usuario} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.Usuario} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.UsuarioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.altaUsuario =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/AltaUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_AltaUsuario,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.Usuario} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.altaUsuario =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/AltaUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_AltaUsuario);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.Usuario,
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 */
const methodDescriptor_UsuarioService_ModificarUsuario = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/ModificarUsuario',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.Usuario,
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.Usuario} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.Usuario} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.UsuarioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.modificarUsuario =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/ModificarUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_ModificarUsuario,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.Usuario} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.modificarUsuario =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/ModificarUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_ModificarUsuario);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 */
const methodDescriptor_UsuarioService_BajaUsuario = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/BajaUsuario',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest,
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.UsuarioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.bajaUsuario =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BajaUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BajaUsuario,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.bajaUsuario =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BajaUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BajaUsuario);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 */
const methodDescriptor_UsuarioService_BuscarPorId = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorId',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest,
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.UsuarioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.buscarPorId =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorId',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BuscarPorId,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.buscarPorId =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorId',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BuscarPorId);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioListResponse>}
 */
const methodDescriptor_UsuarioService_ListarTodos = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/ListarTodos',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.org.example.ProyectoGrpc.grpc.UsuarioListResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.UsuarioListResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.UsuarioListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.UsuarioListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.listarTodos =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/ListarTodos',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_ListarTodos,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.UsuarioListResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.listarTodos =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/ListarTodos',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_ListarTodos);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioEmailRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 */
const methodDescriptor_UsuarioService_BuscarPorEmail = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorEmail',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.UsuarioEmailRequest,
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioEmailRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.UsuarioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.buscarPorEmail =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorEmail',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BuscarPorEmail,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.buscarPorEmail =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorEmail',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BuscarPorEmail);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioNombreRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 */
const methodDescriptor_UsuarioService_BuscarPorNombreUsuario = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorNombreUsuario',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.UsuarioNombreRequest,
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioNombreRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.UsuarioResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioNombreRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.UsuarioResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.buscarPorNombreUsuario =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorNombreUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BuscarPorNombreUsuario,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.UsuarioNombreRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.UsuarioResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.buscarPorNombreUsuario =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/BuscarPorNombreUsuario',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_BuscarPorNombreUsuario);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.LoginRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.LoginResponse>}
 */
const methodDescriptor_UsuarioService_login = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.UsuarioService/login',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.LoginRequest,
  proto.org.example.ProyectoGrpc.grpc.LoginResponse,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/login',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_login,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.UsuarioServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.UsuarioService/login',
      request,
      metadata || {},
      methodDescriptor_UsuarioService_login);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones,
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>}
 */
const methodDescriptor_InventarioDonacionesService_AltaInventario = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/AltaInventario',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones,
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServiceClient.prototype.altaInventario =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/AltaInventario',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_AltaInventario,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServicePromiseClient.prototype.altaInventario =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/AltaInventario',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_AltaInventario);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones,
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>}
 */
const methodDescriptor_InventarioDonacionesService_ModificarInventario = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/ModificarInventario',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones,
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServiceClient.prototype.modificarInventario =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/ModificarInventario',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_ModificarInventario,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServicePromiseClient.prototype.modificarInventario =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/ModificarInventario',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_ModificarInventario);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_InventarioDonacionesService_BajaInventario = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/BajaInventario',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServiceClient.prototype.bajaInventario =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/BajaInventario',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_BajaInventario,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServicePromiseClient.prototype.bajaInventario =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/BajaInventario',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_BajaInventario);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>}
 */
const methodDescriptor_InventarioDonacionesService_BuscarPorId = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/BuscarPorId',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest,
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServiceClient.prototype.buscarPorId =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/BuscarPorId',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_BuscarPorId,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.InventarioIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.InventarioDonaciones>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServicePromiseClient.prototype.buscarPorId =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/BuscarPorId',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_BuscarPorId);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.org.example.ProyectoGrpc.grpc.InventarioListResponse>}
 */
const methodDescriptor_InventarioDonacionesService_ListarTodos = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/ListarTodos',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.org.example.ProyectoGrpc.grpc.InventarioListResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.InventarioListResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.InventarioListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.InventarioListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServiceClient.prototype.listarTodos =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/ListarTodos',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_ListarTodos,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.InventarioListResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.InventarioDonacionesServicePromiseClient.prototype.listarTodos =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.InventarioDonacionesService/ListarTodos',
      request,
      metadata || {},
      methodDescriptor_InventarioDonacionesService_ListarTodos);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
 *   !proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 */
const methodDescriptor_EventoSolidarioService_AltaEvento = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/AltaEvento',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.EventoSolidario} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoSolidario} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.EventoSolidario)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient.prototype.altaEvento =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/AltaEvento',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_AltaEvento,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoSolidario} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient.prototype.altaEvento =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/AltaEvento',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_AltaEvento);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
 *   !proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 */
const methodDescriptor_EventoSolidarioService_ModificarEvento = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/ModificarEvento',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.EventoSolidario} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoSolidario} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.EventoSolidario)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient.prototype.modificarEvento =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/ModificarEvento',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_ModificarEvento,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoSolidario} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient.prototype.modificarEvento =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/ModificarEvento',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_ModificarEvento);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.EventoIdRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_EventoSolidarioService_BajaEvento = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/BajaEvento',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.EventoIdRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.EventoIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient.prototype.bajaEvento =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/BajaEvento',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_BajaEvento,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient.prototype.bajaEvento =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/BajaEvento',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_BajaEvento);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.EventoIdRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 */
const methodDescriptor_EventoSolidarioService_BuscarEventoPorId = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/BuscarEventoPorId',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.EventoIdRequest,
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.EventoIdRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoIdRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.EventoSolidario)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient.prototype.buscarEventoPorId =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/BuscarEventoPorId',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_BuscarEventoPorId,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoIdRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient.prototype.buscarEventoPorId =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/BuscarEventoPorId',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_BuscarEventoPorId);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.org.example.ProyectoGrpc.grpc.EventoListResponse>}
 */
const methodDescriptor_EventoSolidarioService_ListarEventos = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/ListarEventos',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.org.example.ProyectoGrpc.grpc.EventoListResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.EventoListResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.EventoListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.EventoListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient.prototype.listarEventos =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/ListarEventos',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_ListarEventos,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.EventoListResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient.prototype.listarEventos =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/ListarEventos',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_ListarEventos);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 */
const methodDescriptor_EventoSolidarioService_AsignarParticipantes = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/AsignarParticipantes',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest,
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.EventoSolidario)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient.prototype.asignarParticipantes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/AsignarParticipantes',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_AsignarParticipantes,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient.prototype.asignarParticipantes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/AsignarParticipantes',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_AsignarParticipantes);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest,
 *   !proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 */
const methodDescriptor_EventoSolidarioService_QuitarParticipantes = new grpc.web.MethodDescriptor(
  '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/QuitarParticipantes',
  grpc.web.MethodType.UNARY,
  proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest,
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario,
  /**
   * @param {!proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.ProyectoGrpc.grpc.EventoSolidario.deserializeBinary
);


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.ProyectoGrpc.grpc.EventoSolidario)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServiceClient.prototype.quitarParticipantes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/QuitarParticipantes',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_QuitarParticipantes,
      callback);
};


/**
 * @param {!proto.org.example.ProyectoGrpc.grpc.EventoParticipantesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.ProyectoGrpc.grpc.EventoSolidario>}
 *     Promise that resolves to the response
 */
proto.org.example.ProyectoGrpc.grpc.EventoSolidarioServicePromiseClient.prototype.quitarParticipantes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.ProyectoGrpc.grpc.EventoSolidarioService/QuitarParticipantes',
      request,
      metadata || {},
      methodDescriptor_EventoSolidarioService_QuitarParticipantes);
};


module.exports = proto.org.example.ProyectoGrpc.grpc;

